### ISSUE TITLE
crayon colors different on pkgdown/github site?

### ISSUE THREAD

**Issue by SchmidtPaul** [r-lib/downlit#81] opened 2021-03-17 13:26 UTC
<sup>original issue r-lib/crayon#118</sup>

I just started using `crayon::blue()` etc. for my function's `cat()` output e.g. [here](https://github.com/SchmidtPaul/CitaviR/blob/ea4329067f9c602573b3bd2229658faca478ca09/R/find_potential_dups.R#L68). In RStudio Console output it looks nice (see Fig. 1). But [in the html file](https://github.com/SchmidtPaul/CitaviR/blob/ea4329067f9c602573b3bd2229658faca478ca09/docs/reference/find_potential_dups.html#L184) it is not the same blue so that it looks bad on [the github site](https://schmidtpaul.github.io/CitaviR/reference/find_potential_dups.html#examples) (see Fig. 2). I am using an [pkgdown/extra.css](https://github.com/SchmidtPaul/CitaviR/blob/ea4329067f9c602573b3bd2229658faca478ca09/pkgdown/extra.css). 

What would be the best way to get similar/better colors for the github site output?

### Fig. 1
![image](https://user-images.githubusercontent.com/31928213/111469360-e5de7300-8726-11eb-9539-43a2196fcee1.png)

### Fig. 2
![image](https://user-images.githubusercontent.com/31928213/111468376-c5fa7f80-8725-11eb-9ce4-249c07dbc909.png)

### reprex
``` r
# devtools::install_github('SchmidtPaul/CitaviR')
library(CitaviR)

path <- example_xlsx("3dupsin5refs.xlsx")
CitDat <- read_Citavi_xlsx(path) %>%
  find_obvious_dups() %>%
  find_potential_dups()
```
<sup>Created on 2021-03-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

# Edit:
I just noticed that this only occurs for the [example code chunks in Reference](https://schmidtpaul.github.io/CitaviR/reference/find_potential_dups.html#examples) but not in analogous [code chunks in a vignette](https://schmidtpaul.github.io/CitaviR/articles/obv_pot_dups.html#details-2)

**Comment by maelle** [comment] 2021-03-18 14:21
Possibly related to https://github.com/r-lib/pkgdown/issues/1556

**Comment by hadley** [comment] 2021-03-19 11:53
Duplicate of #66 😢

**Closed by hadley** 2021-03-19 11:53 UTC
